#!/bin/bash

H=/Users/scott
/usr/local/bin/tarsnap -c -f code/@`date "+%Y-%m-%dT%H:%M:%S"` $H/code/
/usr/local/bin/tarsnap -c -f dotfiles/@`date "+%Y-%m-%dT%H:%M:%S"` $H/dotfiles/
/usr/local/bin/tarsnap -c -f Documents/@`date "+%Y-%m-%dT%H:%M:%S"` $H/Documents/
